### PR TITLE
Clean repo

### PR DESCRIPTION
**Pull request by gfontenot**
- Remove Pods directory from repo and added it to the gitignore
- Remove xcworkspace from the gitignore
- Removed a bunch of duplicated files
- Reorganize files
- Update podspec

### CODE REVIEW

**Comment by hyperspacemark** [comment]
Having some difficulty getting this to compile. The pods project won't open and it says that Kiwi.h is missing.

**Comment by gfontenot** [comment]
You're opening the .xcworkspace? I was having those errors too, but 1b69ac2 should have fixed them.

**Comment by hyperspacemark** [comment]
Ya opening the .xcworkspace. Ran a pod install which fixed the errors but also dirtied the xcworkspace file. Is this safe to commit and force push or should I just rebase and merge?

**Comment by gfontenot** [comment]
Ah, it doesn't look like I added the xcworkspace to the repo after I took it out of the .gitignore. Add it in a new commit, shouldn't need to force push here after.

**Comment by gfontenot** [comment]
That last commit should fix the xcworkspace getting dirty on `pod install`

**Comment by gfontenot** [comment]
Merged in edf4b80

**Pull request closed without merging**
